### ISSUE TITLE
Projekt na egzamin - zespół DAMKA

### ISSUE THREAD

**Issue by mawala** [egzamin/asi#107]
Właśnie skończyliśmy poprawiać naszą aplikację - dodaliśmy nowe funkcjonalności oraz naprawiliśmy działanie mapki. Ulepszona wersja aplikacji działa pod tym samym linkiem, co poprzednia.

**Comment by wbzyl** [comment]
Poprawiłem oceny. Proszę dopisać w pliku README.md w repozytorium dlaczego mapki nie działały i co trzeba było poprawić aby zadziałały.
