### ISSUE TITLE
Prośba o ocenienie projektu na zaliczenie Paweł Wilamowski

### ISSUE THREAD

**Issue by pwilamowski** [egzamin/asi#118]
Projekt na zaliczenie:
https://github.com/pwilamowski/asi-zaliczenie
Projekt na egzamin w którym brałem udział:
https://github.com/pcendrowski/asi-projekt-egzamin

**Comment by wbzyl** [comment]
Termin zaliczania już dawno minął. 
Dlatego ma pan niezaliczone laboratoria.
