### ISSUE TITLE
Poprawa projektu

### ISSUE THREAD

**Issue by mjaszczak** [egzamin/asi#80]
link do wdrożonej aplikacji: https://ruby-laptopy-mjaszczak.c9users.io/
Mariusz Jaszczak

**Comment by wbzyl** [comment]
<img width="799" alt="zrzut ekranu 2016-05-30 o 11 04 45" src="https://cloud.githubusercontent.com/assets/8049/15645032/9098c138-2656-11e6-9636-41576386f322.png">
